# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: Dockerfile

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install dependencies
      run: npm install
    
    - name: install dependencies
      run: npm run compile

    - name: install dependencies
      run: npm run lint

    - name: install dependencies
      run: npm run test

    - name: create vscode package
      run: vsce package'
      
    - name: Upload a Build Artifact
      if: contains('refs/heads/master', github.ref)
      uses: actions/upload-artifact@v2
      with:
        path: ./*.vsix



    
